alert("hi te shai and gie.....")
alert("nagtry lang ko ug code......")
alert("one question lang.")
alert("how is IT Journey?")
alert(" is it good or bad?")
alert("anyways javascript gamit nako ani HAHAHAHHAHAHAH")